[package]
name = "uberclone"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-ws = "0.3.0"
futures-util = "0.3.31"
uuid = {version = "1.11.0" ,features=["v4"]}
sede ={ version ="1.0.216", features=["derive"]}
redis = { version = "0.27.6", features = ["async-std-comp"] }